# Generated by Django 4.0.2 on 2022-02-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(verbose_name='Original URL')),
                ('hash', models.CharField(blank=True, max_length=20, null=True, verbose_name='Original URL hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time URL created at')),
            ],
        ),
    ]
